// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(App.app(/* () */0), "root");

/*  Not a pure module */
